# https://rust-lang.github.io/rustfmt/?version=v1.8.0&search=#config
edition = "2024"
use_small_heuristics = "Max"
newline_style = "Unix"

max_width = 100
# nightly
# imports_granularity = "Module"
# nightly
# group_imports = "StdExternalCrate"
# nightly
# reorder_impl_items = true
# unstable
# unstable_features = true
# wrap_comments = true
